openapi: 3.0.0
info: 
  title: Ordered ToDo list 
  version: "1.0"
security:
  - basicAuth: []
paths:
  /register:
    post:
      security: []
      tags:
        - users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username: 
                  type: string
                password:
                  type: string
      responses:
        400:
          description: 'Bad request'
          content:
            application/json:
              example: '{"status_code": "400 Bad Request", "detail": "Request has empty password"}'
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
        409:
          description: 'Username conficts with already exists'
          content:
            application/json:
              example: '{"status_code": "409 Conflict", "detail": "User with username = %user% already exists"}'
              schema:
                $ref: '#/components/schemas/ErrorResponseSchema'
        200:
          description: 'User registered'
  /list/my:
    get:
      tags:
        - lists
      description: "Returns user owned list"
      responses:
        200:
          description: "Ok"
          content:
            application/json:
              schema:
                type: object
                properties:
                  list_id:
                    type: integer
  /list/:
    get:
      tags:
        - lists
      description: "Get all lists ids"
      responses:
        200:
          description: "Ok"
          content:
            application/json:
              schema:
                type: object
                properties:
                  list_ids:
                    type: array
                    items:
                      type: integer
    post:
      tags:
        - lists
      description: "Create list"
      responses:
        200:
           description: "Ok"
  /list/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
        description: "List id"
    put:
      tags:
        - lists
      description: "Modify list"
      responses:
        404:
          $ref: '#/components/responses/ListNotFound'
    get: 
      parameters:
        - in: "query"
          name: count
          required: false
          schema:
            type: integer
          description: "Specify maximum entries in response"
        - in: "query"
          name: offset
          required: false
          schema:
            type: integer
          description: "Entries offset"
      tags:
        - lists
      description: "Get list"
      responses:
        200:
          description: "Ok"
          content:
            application/json:
              schema:
                type: object
                properties: 
                  total_entries:
                    type: integer
                  entries:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        priority:
                          type: integer
                        description:
                          type: string
        404:
          $ref: '#/components/responses/ListNotFound'
    delete:
      tags:
        - lists
      description: "Delete entire list"
      responses:
        404:
          $ref: '#/components/responses/ListNotFound'
  /list/{id}/entry:
    parameters:
      - in: "path"
        name: "id"
        required: true
        schema:
           type: integer
    post:
      tags:
        - entry
      description: 'Create new entry'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                value: 
                  type: string
      responses:
        200:
           description: "Ok"
  /list/{list_id}/entry/{entry_id}:
    parameters:
      - in: "path"
        name: "list_id"
        schema:
           type: integer
        required: true
      - in: "path"
        name: "entry_id"
        schema:
           type: integer
        required: true
    put:
      tags:
        - entry
      description: 'Modify entry'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                set_priority:
                  type: integer
      responses:
        200:
          description: "Ok"
        404:
          $ref: '#/components/responses/EntryNotFound'
    delete:
      tags:
        - entry
      description: 'Delete entry'
      responses:
        200:
          description: "Ok"
        404:
          $ref: '#/components/responses/EntryNotFound'
components:
  responses:
    EntryNotFound:
      description: "Entry not found"
      content:
        application/json:
          example: '{"status_code": "404 Not Found", "detail": "Entry with id %id% in list %list_id% not found"}'
    ListNotFound:
      description: "List not found"
      content:
        application/json:
          example: '{"status_code": "404 Not Found", "detail": "List with id %id% not found"}'
          schema:
            $ref: '#/components/schemas/ErrorResponseSchema'
  schemas:
    ErrorResponseSchema:
      type: object
      properties:
        status_code:
          type: string
        detail:
          type: string
  securitySchemes:
    basicAuth: 
      type: http
      scheme: basic
